services:
  postgres:
    image: postgres:16
    container_name: zypocare-postgres
    environment:
      POSTGRES_DB: zypocare
      POSTGRES_USER: zypocare
      POSTGRES_PASSWORD: zypocare_dev_password
    ports: ["5433:5433"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: zypocare-redis
    ports: ["6379:6379"]
    healthcheck:
     test: ["CMD", "redis-cli", "ping"]
     interval: 5s
     timeout: 3s
     retries: 20

  nats:
    image: nats:2.10-alpine
    container_name: zypocare-nats
    # -js: Enable JetStream
    # -sd /data: Store data in the /data directory (mapped to volume)
    # -m 8222: Enable HTTP Monitoring
    command: "-js -sd /data -m 8222"
    ports: 
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: zypocare-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8080:8080"]
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: zypocare-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports: ["4317:4317", "4318:4318", "8889:8889"]

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: zypocare-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: zypocare-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports: ["3001:3000"]
    volumes:
      - grafana_data:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: zypocare-jaeger
    ports: ["16686:16686", "14250:14250", "14268:14268"]

volumes:
  postgres_data:
  grafana_data:
  nats_data: